language: python

python:
  - 2.7

install:
  - pip install requests markdown beautifulsoup4

script:
  - python check_urls.py sources-ru.md
  - python check_urls.py sources-non-ru.md

notifications:
  email:
    - estetus+travis-ci@gmail.com
