language: ruby

rvm:
  - 2.2

before_script:
  - gem install awesome_bot

script:
  - awesome_bot sources-ru.csv --allow-redirect --allow-ssl --white-list http://bronnikovy.ru/,http://www.mukhanov.ru/

notifications:
  email:
    recipients:
      - estetus+travis-ci@gmail.com
    on_success: change
    on_failure: always
